apiVersion: apps/v1
kind: Deployment
metadata:
  name: myDep
  labels: 
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
     env: prod
  template:
    metadata:
     name: myapp-pod
     labels:
       env: prod
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80