apiVersion: v1
kind: Pod
metadata:
  name: mariadb
spec:
  containers:
  - name: maria
    image: mariadb
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: "MARIADB_ROOT_PASSWORD"
        valueFrom:
          secretKeyRef:
            name:  mariadb-secret
            key: MARIADB_ROOT_PASSWORD