apiVersion: v1
kind: Pod
metadata:
  name: tow-containers-pod
spec:
  restartPolicy: Never
  volumes:
    - name: shared-erea
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-erea
          mountPath: /us/share/nginx/html
      resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "1"
    - name: alpine
      image: alpine
      volumeMounts:
        - name: shared-erea
          mountPath: /pod-page
      command: ["/bin/bash"]
      args: ["-c", "echo hello tarek > /pod-page/index.html "]
      